### ISSUE TITLE
Implement Share Management Functions

### ISSUE THREAD

**Issue by jmonteer** [jmonteer/yearn-vaults-v3#18]
Implement Share Management Functions
------
**Description:** 
Implement deposit
Implement withdraw
Implement share value functions
Implement ERC20 functions

**Dependencies:**
NA
**Acceptance criteria:** 
Required functions are implemented
**Payment Trigger:** 
PR is merged
**Category:**
DEV
**Level:**
1

**Comment by pandadefi** [comment]
Have we decided on 4626?

**Comment by anticlimactic** [comment]
I believe @jmonteer wants 4626 to be implemented as a wrapper. This will provide flexibility in allowing integrators to either integrate directly with the vault to deposit / withdraw (relevant for withdrawal, since you can select which strategies you wish to withdraw from) or being lazy and integrating through the wrapper.

**Comment by jmonteer** [comment]
Yes!

@pandadefi and I discussed this privately but the idea is to leave core code non-compliant and then build a yRouter or yShareToken that is compliant with erc4626
